repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-added-large-files
      args: [--maxkb=520]
    - id: check-ast
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-yaml
      exclude: templates\/.*
    - id: check-json
    - id: debug-statements
    - id: end-of-file-fixer
      exclude: vendor\/.*
    - id: trailing-whitespace
      exclude: vendor\/.*
- repo: https://github.com/tekwizely/pre-commit-golang
  rev: v0.8.3
  hooks:

  # Go Build
  - id: go-build-mod

  # Go Test
  - id: go-test-mod

  # Go Vet
  - id: go-vet-mod

  # GoSec
  - id: go-sec-mod

  # Formatters
  - id: go-returns # replaces go-imports & go-fmt

  # Style Checkers
  - id: go-lint
    exclude: (vendor\/)|(internal\/mock\/)

  # GolangCI-Lint
  # - Fast Multi-Linter
  # - Can be configured to replace MOST other hooks
  # - Supports repo config file for configuration
  # - https://github.com/golangci/golangci-lint
  #
  - id: golangci-lint-mod
